name: CI Pipeline

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dotnet:
    name: .NET Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  docker:
    name: Docker Image CI
    needs: dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Extract version from .csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/BlogSystem.API/BlogSystem.API.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file src/BlogSystem.API/Dockerfile --tag blogsystem-api:${{ env.VERSION }}
